---
layout: work-with-us-layout
title: Visual Designer
description: We are looking for an in-house visual designer for Fields of View will work on visual content for FoV in both the digital and print medium. The in-house visual designer is expected to be able to draw out narratives from different projects and represent it in the visual medium. The designer must also be able to use visualisations to make sense of data, elucidate processes and represent systems. The primary aim is to reduce dependence on written form for better accessibility, considering the Indian context. Producing project specific visual content such as infographics, visualisations, web interfaces, dashboards, presentations and more.<br/><br/>Apart from project specific work, the in-house visual designer also works as a communications designer responsible for promotion/presentation material such as posters, booklets, brochures, visiting cards, web presence, presentations. This requires skill-sets that borrow from both, a designer and a front-end developer.<br/><br/>Fields of View is an interdisciplinary group - therefore, the designer has to be able to work with people from diverse backgrounds.
skills: The designer will be working on multiple projects - therefore, ability to switch contexts, and deliver according to timelines is a must.<br/><br/>We are a not-for-profit research organisation and the position is based in Bangalore. Women visual designers are encouraged to apply.<br/><br/>For details of remuneration and any other information, please mail <a href = "mailto:work@fieldsofview.in?subject=Application for the position of Visual Designer" class="mailid">work@fieldsofview.in</a> with your CV.<br/><br/><ul><p class=simple-content style="font-size:14pt"><b>Tools and technologies</b></p><li><p class="simple-content">Offline</p><ul><li><p class="simple-content">GIMP/Adobe Photoshop- Knowledge of and experience with a good image manipulation tool</p></li><li><p class="simple-content">Inkscape/Adobe Illustrator- Experience with a vector creation and editing tool</p></li><li><p class="simple-content">Scribus/Adobe InDesign- Experience with a Desktop Publishing tool for document creation</p></li><li><p class="simple-content">Multimedia Presentation tools- Microsoft Power point, LibreOffice/OpenOffice Impress, Prezi</p></li></ul></li><li><p class="simple-content">Web</p><ul><li><p class="simple-content">HTML</p></li><li><p class="simple-content">CSS</p></li><li><p class="simple-content">JavaScript (jQuery/Vanilla)</p></li><li><p class="simple-content">PHP</p></li><li><p class="simple-content">MySQL</p></li><li><p class="simple-content">Git</p></li><li><p class="simple-content">CMS (Drupal)</p></li></ul></li><li><p class="simple-content">Bonus points for</p><ul><li><p class="simple-content">Being up-to-date with the latest technologies and concepts in design.</p></li><li><p class="simple-content">Examples of scalable, clean, collaborative and maintainable code.</p></li><li><p class="simple-content">Ability to use existing plug-ins effectively.</p></li></ul></li></ul>
ide: visualdesigner
tag: VisualDesigner
category: jd
permalink: /projects/work-with-us/visual-designer/
---